Caproto GeRM IOC
NSLS-II-HEX/profile_collection pull request #4
Opened 2024-01-23 05:40 UTC by mrakitin

This work is to wrap file saving into EPICS via a Caproto IOC which works in tandem with the main IOC for GeRM.

2024-01-23 05:42 UTC, mrakitin commented
@danielballan, does the implementation follow caproto standard approaches?

2024-01-23 14:04 UTC, jwlodek requested changes

2024-01-23 14:04 UTC, jwlodek commented on caproto-ioc-germ/germ_ioc.py
> +EPICS_CAS_AUTO_BEACON_ADDR_LIST=no EPICS_CAS_BEACON_ADDR_LIST=127.0.0.1 python germ_ioc.py -v
May want to note that on the actual IOC server the ADDR_LIST will need to be the IP of the EPICS interface of the server

2024-01-23 14:04 UTC, jwlodek commented on caproto-ioc-germ/germ_ioc.py
> +    PV_PREFIX_CURLED = "XF:27ID1-ES{GeRM-Det:1}"
May want to refactor to support passing these prefixes as args? Will probably need to re-use this for other beamlines that get the GeRM

2024-01-23 16:01 UTC, danielballan commented on caproto-ioc-germ/germ_ioc.py
> +    PV_PREFIX_CURLED = "XF:27ID1-ES{GeRM-Det:1}"
Agreed.

There is a lower-level API that gives you access to the `ArgumentParser` instance, `parser`, and enables you to extend it with additional args. See example https://github.com/caproto/caproto/blob/46020e4816c7dbe8ccae9b7f0af362ce9a7f4f07/caproto/ioc_examples/formula_ioc.py#L154-L171

2024-01-23 16:01 UTC, danielballan commented on caproto-ioc-germ/germ_ophyd.py
> +            raise ValueError("Failed to save data due to: {}".format(e))
Not sure why we would catch and re-raise as `ValueError`. It could be an `OSError` or something else.

2024-01-23 16:01 UTC, danielballan commented on caproto-ioc-germ/germ_ioc.py
> +        value="/tmp",
Maybe use `tempfile.NamedTemporaryDirectory()` so that if this is accidentally left as its default value, it's easier to clean up?

2024-01-23 16:01 UTC, danielballan commented on caproto-ioc-germ/germ_ophyd.py
> +ROOT_DIR = "/tmp"
Ditto about the temp dir

2024-01-23 22:25 UTC, mrakitin commented on caproto-ioc-germ/germ_ioc.py
> +        value="/tmp",
It worked for files only, not dirs: `from tempfile import NamedTemporaryFile`.
I'll use `from tempfile import mkdtemp` instead.

2024-02-06 23:02 UTC, mrakitin commented
All these changes and suggestions were implemented via the https://github.com/NSLS-II-HEX/hextools package. Closing w/o merging.

2024-02-06 23:02 UTC, closed without merging